import type { NoticeModel } from "./model/NoticeModel";

export const mockNotices: NoticeModel[] = [
  {
    id: "1",
    title: "Annual Sports Day Announcement",
    description: "The Annual Sports Day will be held on December 15, 2024. All students are required to participate.",
    category: "event",
    priority: "high",
    publishedDate: "2024-11-20",
    expiryDate: "2024-12-16",
    author: "Sports Department",
    department: "Physical Education",
    audience: "students",
    attachments: ["sports_schedule.pdf", "registration_form.docx"],
    isPublished: true,
    views: 245,
    color: "#3B82F6"
  },
  {
    id: "2",
    title: "Semester Final Exam Schedule",
    description: "Final exam schedule for Fall 2024 semester has been published. Please check the academic portal.",
    category: "academic",
    priority: "critical",
    publishedDate: "2024-11-18",
    expiryDate: "2024-12-30",
    author: "Examination Cell",
    department: "Academic",
    audience: "all",
    attachments: ["exam_schedule.pdf"],
    isPublished: true,
    views: 1024,
    color: "#EF4444"
  },
  {
    id: "3",
    title: "Library Maintenance Notice",
    description: "Central library will be closed for maintenance from December 1-3, 2024.",
    category: "general",
    priority: "medium",
    publishedDate: "2024-11-15",
    expiryDate: "2024-12-04",
    author: "Library Administration",
    department: "Library",
    audience: "all",
    isPublished: true,
    views: 156,
    color: "#10B981"
  },
  {
    id: "4",
    title: "Faculty Meeting Reminder",
    description: "Monthly faculty meeting scheduled for November 25, 2024 at 2:00 PM in Conference Room A.",
    category: "announcement",
    priority: "medium",
    publishedDate: "2024-11-10",
    author: "Dean's Office",
    department: "Administration",
    audience: "faculty",
    isPublished: true,
    views: 89,
    color: "#8B5CF6"
  },
  {
    id: "5",
    title: "Cyber Security Awareness Workshop",
    description: "Join our free workshop on cyber security best practices for students and staff.",
    category: "event",
    priority: "high",
    publishedDate: "2024-11-05",
    expiryDate: "2024-11-30",
    author: "IT Department",
    department: "Information Technology",
    audience: "all",
    attachments: ["workshop_details.pdf", "agenda.docx"],
    isPublished: true,
    views: 312,
    color: "#F59E0B"
  },
  {
    id: "6",
    title: "Campus WiFi Upgrade",
    description: "Notice about upcoming campus WiFi network upgrade during maintenance hours.",
    category: "general",
    priority: "low",
    publishedDate: "2024-11-01",
    author: "Network Services",
    department: "IT",
    audience: "all",
    isPublished: false,
    views: 45,
    color: "#6B7280"
  }
];